### PR TITLE
add Movie Categories UI and fetch the movie genres data

### PR DESCRIPTION
**Pull request by ZJYLBJMayDay**

### CODE REVIEW

**Review by xiaoqing-z — COMMENTED** [review]
Please delete unnecessary code before uploading.

**Review by ghost — COMMENTED** [review]
.eslintcache file can be ignored by .gitignore

**Review by xiaoqing-z — COMMENTED** [review]
looks good

**Review by ghost — APPROVED** [review]
Issues are solved, and features had been added fairly enough

**Pull request merged**
